"use client"
import { anton, architectsDaughter } from '@/lib/fonts'
import Image from 'next/image';
// use AVIF variants generated by the conversion script
const heroSrc = '/hero.avif';
const hero1Src = '/hero1.avif';
const hero2Src = '/hero2.avif';
const hero3Src = '/hero3.avif';
const hero4Src = '/hero4.avif';

import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Autoplay } from "swiper/modules";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

const projectImages = [
    { id: 1, src: heroSrc, alt: 'Project 1' },
    { id: 2, src: hero1Src, alt: 'Project 2' },
    { id: 3, src: hero2Src, alt: 'Project 3' },
    { id: 4, src: hero3Src, alt: 'Project 4' },
    { id: 5, src: hero4Src, alt: 'Project 5' },
];


function ProjectSwipper() {
    return (
        <section className='w-full flex flex-col items-center justify-center px-4 sm:px-6 overflow-hidden'>

            <h2 className={`max-w-5xl text-[26px] sm:text-[36px] md:text-[44px] font-black ${anton.className} text-center mt-14 sm:mt-20 leading-normal sm:leading-tight`}>
                At <span className={`${architectsDaughter.className} text-[#C24700]`}>Scalix</span> Web Agency, we build <span className={`${architectsDaughter.className} text-[#C24700]`}>modern applications</span>{" "}
                for businesses</h2>
            <section className='relative border w-full min-h-120 sm:min-h-152 lg:min-h-192 overflow-hidden bg-[#15157D] mt-10 sm:mt-20 flex items-center justify-center py-10 sm:py-14'>
                {/* Orange glow - left bottom */}
                <div className="absolute -bottom-24 -left-24 sm:-bottom-40 sm:-left-40 h-48 w-60 sm:h-80 sm:w-120 rounded-full bg-[#FFA369] blur-[180px]" />

                {/* Blue glow - right bottom */}
                <div className="absolute -top-20 -right-24 sm:-top-40 sm:-right-32 h-40 w-56 sm:h-72 sm:w-120 rounded-full bg-[#D6F1FF] blur-[180px]" />

                <div className='relative w-full max-w-6xl aspect-video mx-auto shadow-2xl z-20'>

                    <Swiper
                        modules={[Navigation, Pagination, Autoplay]}
                        spaceBetween={30}
                        slidesPerView={1}
                        navigation={true}
                        pagination={{ clickable: true }}
                        autoplay={{ delay: 2000, disableOnInteraction: false }}
                        loop={true}
                        grabCursor
                        className="w-full h-full"
                    >
                        {
                            projectImages.map((image, index) =>
                                <SwiperSlide key={image.id}>
                                    <div className="w-full h-full flex items-center justify-center">
                                        <Image
                                            src={image.src}
                                            alt={image.alt}
                                            width={1200}
                                            height={675}
                                            sizes="(max-width: 768px) 100vw, 1200px"
                                            className="object-contain rounded-lg w-full h-auto"
                                            placeholder="blur"
                                            blurDataURL={"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10' viewBox='0 0 10 10'><rect width='10' height='10' fill='%2315157D'/></svg>"}
                                            {...(index === 0 ? { priority: true } : { loading: "lazy" })}
                                        />
                                    </div>
                                </SwiperSlide>
                            )
                        }
                    </Swiper>

                </div>


            </section>
        </section>
    )
}

export default ProjectSwipper